### ISSUE TITLE
How to handle the Oauth 2.0 redirect 

### ISSUE THREAD

**Issue by adriatic** [aurelia-auth0/new-samples#1]
I am looking for the best way to handle the following situation, that takes place in the context of Aurelia SPA application authentication with Auth0 SaaS platform.

The authentication process consists of the following steps:

#### Step 1 
The SPA app registers its intent to authenticate itself:
```
auth0 = new auth0.WebAuth({
    domain: AUTH_CONFIG.domain,
    clientID: AUTH_CONFIG.clientID,
    redirectUri: AUTH_CONFIG.callbackUri,
    audience: `https://${AUTH_CONFIG.domain}/userinfo`,
    responseType: 'token id_token',
    scope: 'openid'
  });
```

#### Step 2
The SPA app issues the authorize request:
```
auth0.authorize();
```

at this point the SPA app "dies" the `auth0.authorize();` is implemented as "redirect" to the server

#### Step 3

Authentication server responds by issuing the redirect to the URI (`redirectUri`) defined in Step 1. This response is in the form of a "hash-segment" which contains the **[JWT token](https://jwt.io/)** for subsequent authorization requests:

![image](https://user-images.githubusercontent.com/2712405/39723703-a34f6f66-5214-11e8-9906-fa1d76a9920c.png).

Here is the Chrome debugger's view of this situation:

![image](https://user-images.githubusercontent.com/2712405/39723947-5752dc28-5215-11e8-813b-a72bd4b72f57.png)

This token is then parsed using the Auth0 service and used in  subsequent transactions with the Auth0 service platform. 

___Problem:___  _My application is the current standard CLI - webpack 4 based and it grabs on this same hash-segment perceiving it as the routing information, as shown below:_

![image](https://user-images.githubusercontent.com/2712405/39724322-773dd816-5216-11e8-9f8f-66fd9bb73721.png)

**Comment by aaguiarz** [comment]
In Angular, we do _this.router.navigate(['/home']);_, in React _history.replace('/home');_, and even in Vanilla Javascript ones we remove it so it's not seen in the URL _ window.location.hash = '';_, so the solution seems consistent and correct.

**Comment by adriatic** [comment]
With the exception of my **[just added section](https://github.com/aurelia-auth0/new-samples/issues/7#issuecomment-390372209)** we can close this issue.
