### ISSUE TITLE
Write all Aurelia Quickstarts guides

### ISSUE THREAD

**Issue by adriatic** [aurelia-auth0/new-samples#15]
Unless advised differently by @aaguiarz, I plan to write them using the **[Plain Vanilla SPA](https://auth0.com/docs/quickstart/spa/vanillajs)** as model

![image](https://user-images.githubusercontent.com/2712405/40317909-e64ec21c-5cf0-11e8-9895-a8101535cf24.png)

**Comment by brunokrebs** [comment]
Hey there. I'm not really following why are you creating sooo many issues. I guess this is how you like to keep track of what is missing and what you will focus on next.

How ever, it is a little bit hard for me to keep up with everything, so I will ask you that if you have any technical issue that you need help, please, mention me (@brunokrebs) so I can understand that you need my help...

**Comment by adriatic** [comment]
>  I guess this is how you like to keep track of what is missing and what you will focus on next.

Correct assumption 😄 . As we do have a direct channel at Slack, you should not pay any attention to my work, particularly since all I do at the moment is Quick Starts related (when I finish the code, I will follow up with all Quick Start "manuals".

**Comment by adriatic** [comment]
Proper communications channels established
