### ISSUE TITLE
How to render the Log In Logout toggle cursor as a "hand"

### ISSUE THREAD

**Issue by adriatic** [aurelia-auth0/new-samples#9]
The code for the **[`nav-bar`](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/01-Login/src/nav-bar.html)** is created as a view-only (HTML) component - a part of Aurelia standard practice. The menu-bar items are organized in two groups:
1. **[Collection of standard menu-items](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/01-Login/src/nav-bar.html#L12-L16)** rendered in a loop across all items that appear in **[`config.map`](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/01-Login/src/app.js#L14-L21)** object.
2. **[`Log In / Log Out`](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/01-Login/src/nav-bar.html#L18-L27)** toggle items, which are not a part of the Aurelia routing system (as they should not be a part of routing).

### Issue: 
How can I ensure that the  **[`Log In / Log Out`](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/01-Login/src/nav-bar.html#L18-L27)** toggle items behave the same as the standard menu items with respect to cursor hover - to render the cursor as "hand"?

**Comment by adriatic** [comment]
I temporarily fixed this issue by adding the class `nav-link` to the  **[`Log In`](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/01-Login/src/nav-bar.html#L21)** / **[`Log Out`](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/01-Login/src/nav-bar.html#L25)** toggle ___as well as added___ my own **[definition of that class](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/01-Login/static/styles.css#L1-L3)** in the **[`styles.css`](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/01-Login/static/styles.css)** file.

_This is the hack created to address the likely redefinition of this class somewhere._

**Comment by brunokrebs** [comment]
Your approach is correct and is good enough.

Another approach would be using this CSS rule:

```css
.navbar a {
  cursor: pointer;
}
```

Or this one:

```css
.navbar .navbar-nav a {
  cursor: pointer;
}
```

All three (yours and these two) achieve the same thing and are correct. Your choice. 😄
